<?php
$attribs = $isNoidReady ? array('disable' => true) : null;
?>
<p class="explanation">
<?php
    echo $this->translate('Ark allows to creates and manages unique, universel and persistent ark identifiers.') . '<br />';
    echo $this->translate('See %s and %sthe official help%s for more informations.',
        '<a href="https://github.com/Daniel-KM/ArkForOmeka">ReadMe</a>',
        '<a href="https://confluence.ucop.edu/display/Curation/ARK">', '</a>');
?>
</p>
