<?php // This shoud returns a brief machine- and eye-readable metadata record (not the full Dublin Core).
$title = $resource->value('dcterms:title', ['type' => 'literal']);
if (empty($title)) {
    $title = $this->translate('[No title]');
}
$creators = $resource->value('dcterms:creator', ['type' => 'literal', 'all' => true]);
$publisher = $resource->value('dcterms:publisher', ['type' => 'literal']);
$date = $resource->value('dcterms:date', ['type' => 'literal']);
$description = $resource->value('dcterms:description', ['type' => 'literal']);

function _oneCleanLine($string)
{
    return trim(preg_replace('/\s\s+/', ' ', $string));
}
?>
erc:
<?php foreach ($creators as $creator): ?>
who:    <?php echo _oneCleanLine($creator) . PHP_EOL; ?>
<?php endforeach; ?>
<?php if ($publisher): ?>
who:    <?php echo _oneCleanLine($publisher) . PHP_EOL; ?>
<?php endif; ?>
<?php if (empty($creators) && empty($publisher)): ?>
who:    <?php echo '(:unkn) anonymous' . PHP_EOL; ?>
<?php endif; ?>
what:   <?php echo ($title ?: '(:unas) value unassigned') . PHP_EOL; ?>
when:   <?php echo ($date ?: '(:unav) value unavailable, possibly unknown') . PHP_EOL; ?>
where:  <?php echo $this->ark($resource)->getAbsoluteUrl() . PHP_EOL; ?>
<?php if ($description): ?>
about-how:    <?php echo _oneCleanLine($description) . PHP_EOL; ?>
<?php endif; ?>
<?php if ($note = $this->setting('ark_note')): ?>
note:   <?php echo _oneCleanLine($note) . PHP_EOL; ?>
<?php endif; ?>
<?php echo $policy ? $this->setting('ark_policy_statement') : '' ?>
