# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Noid
version:      1.1.0-0.424-php
version_from: VERSION
installdirs:  site
requires:
    BerkeleyDB:                    0

distribution_type: module
